version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-db-new
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    networks:
      - app-network

networks:
  app-network:
